project_id = "uyeqdokcwmcxuxuwwjnj"

[functions.send-alerts]
verify_jwt = false

[functions.generate-social-image]
verify_jwt = false

[functions.process-reminders]
verify_jwt = false

[functions.send-push-test]
verify_jwt = true

[functions.cron-send-reminders]
verify_jwt = false